controller_list:
  - name: fake_mia_index_controller
    type: $(arg execution_type)
    joints:
      - j_index_fle
  - name: fake_mia_mrl_controller
    type: $(arg execution_type)
    joints:
      - j_mrl_fle
  - name: fake_mia_thumb_controller
    type: $(arg execution_type)
    joints:
      - j_thumb_fle
initial:  # Define initial robot poses.
  - group: mia_index
    pose: open_adducted