# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: mia_index
  joint_model_group_pose: open_adducted

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface

hardware_interface:
  joints:
    - j_index_fle
    - j_mrl_fle
    - j_thumb_fle
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: mia_hand_index_vel_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_index_fle

      
  - name: mia_hand_mrl_vel_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_mrl_fle
      
      
  - name: mia_hand_thumb_vel_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_thumb_fle

