<?xml version="1.0"?>
<!--
 Software License Agreement (BSD License)
 Copyright Â© 2022 belongs to Shadow Robot Company Ltd.
 All rights reserved.
 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
   3. Neither the name of Shadow Robot Company Ltd nor the names of its contributors
      may be used to endorse or promote products derived from this software without
      specific prior written permission.
 This software is provided by Shadow Robot Company Ltd "as is" and any express
 or implied warranties, including, but not limited to, the implied warranties of
 merchantability and fitness for a particular purpose are disclaimed. In no event
 shall the copyright holder be liable for any direct, indirect, incidental, special,
 exemplary, or consequential damages (including, but not limited to, procurement of
 substitute goods or services; loss of use, data, or profits; or business interruption)
 however caused and on any theory of liability, whether in contract, strict liability,
 or tort (including negligence or otherwise) arising in any way out of the use of this
 software, even if advised of the possibility of such damage.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:if value="${mounting_plate}">
    <xacro:property name="mounting_plate_offset" value="0.005" />
  </xacro:if>
  <xacro:unless value="${mounting_plate}">
    <xacro:property name="mounting_plate_offset" value="0.0" />
  </xacro:unless>
  <xacro:macro name="forearm" params="hand_type:=^ hand_version:=^ prefix:=^ mounting_plate:=^">
    <link name="${prefix}forearm">
      <inertial>
        <origin xyz="0 0 0.09" rpy="0 0 0" />
        <!-- TODO: This is a rough estimate. Total hand is 2359g -->
        <mass value="1.8" />
        <inertia ixx="0.108" ixy="0.0" ixz="0.0" iyy="0.108" iyz="0.0" izz="0.054" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${mounting_plate_offset}" rpy="0 0 ${pi/2}" />
        <geometry name="${prefix}forearm_visual">
          <mesh filename="package://sr_description/meshes/components/forearm/forearm_${hand_version}.dae" scale="1.0 1.0 1.0" />
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${0.065+mounting_plate_offset}" rpy="0 0 0" />
        <geometry name="${prefix}forearm_collision">
          <box size="0.120 0.109 0.130" />
        </geometry>
      </collision>
      <!-- mounting plate in case the hand is attached to an arm -->
      <xacro:if value="${mounting_plate}">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="${prefix}mounting_plate">
            <mesh filename="package://sr_description/meshes/components/mounting_plate/mounting_plate_${hand_version}.dae" scale="0.001 0.001 0.001" />
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0.002" rpy="0 0 0" />
          <geometry>
            <box size="0.120 0.109 0.006" />
          </geometry>
        </collision>
      </xacro:if>
    </link>
    <gazebo reference="${prefix}forearm">
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:macro>
</robot>
