# mia hand velocity controller params

thumb_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_thumb
  pid: {p: &p_gain 2.0, i: &i_gain 5.0, d: &d_gain 0.0,
        i_clamp_min: &i_clamp_min 0.0, i_clamp_max: &i_clamp_max 10.0, antiwindup: &awup false} # define gains one time only and then replicate using *p_gain (for example)

index_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_index
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_clamp_min, i_clamp_max: *i_clamp_max, antiwindup: *awup}
        
mrl_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_mrl
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_clamp_min, i_clamp_max: *i_clamp_max, antiwindup: *awup}

thumb_mcp_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: j_thumb_mcp
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_clamp_min, i_clamp_max: *i_clamp_max, antiwindup: *awup}
